### ISSUE TITLE
#[must_use] instead of drop_bomb?

### ISSUE THREAD

**Issue by axelkar** [lunacookies/lang#1]
https://lunacookies.github.io/lang/15/#fn:1

I think it's possible nowadays via the `must_use` attribute:
- https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute
- https://drashti-shah.medium.com/leveraging-must-use-for-robust-rust-development-805557021cc3

I'm sorry for necroing but I also want to know your view on it :)

**Comment by lunacookies** [comment]
I only realized while I was typing up a reply to you that this wouldn’t quite work.

Let’s start from the simplest case – suppose we’ve just written `p.start()` somewhere randomly. With `drop_bomb` we get a panic at runtime, while with `#[must_use]` we get a warning telling us that the `Marker` value can’t just be discarded like that.

Next, suppose we’ve created a marker with `let m = p.start()`, but forget to call `m.complete(p, kind)` – with `drop_bomb` we again get a panic, but with `#[must_use]` we get a warning about `m` being an unused local. We would’ve gotten the same warning even without `#[must_use]`, because from the compiler’s perspective the marker is “used” by it being stored in that `m` local, regardless of whether the local is ever accessed.

In this scenario, had we actually used `m` at some point (and never called `Marker::complete`), we wouldn’t get a warning with `#[must_use]` where we would’ve panicked with `drop_bomb`. In some complex scenarios you can actually end up needing to pass markers around to grammar functions, so it isn’t like this is a hypothetical. I’ve never had to do this in any of the parsers I’ve written, but [it can happen](https://github.com/rust-lang/rust-analyzer/blob/d9c29afaee6cb26044b5a605e0073fcabb2e9722/crates/parser/src/grammar/items/adt.rs#L20).

Also there’s no need to apologize, I’m happy to see people are still finding this useful :D
